# Generated by Django 2.0.2 on 2019-02-11 19:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='appYears',
            fields=[
                ('year', models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='areaCaus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=64)),
                ('code', models.CharField(default='', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='avion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField(default=1)),
                ('hRecALB', models.CharField(default='', max_length=200)),
                ('hRecV10', models.CharField(default='', max_length=200)),
                ('hRecRL8', models.CharField(default='', max_length=200)),
                ('hRecM60', models.CharField(default='', max_length=200)),
                ('hLTALB', models.CharField(default='', max_length=200)),
                ('hLTV10', models.CharField(default='', max_length=200)),
                ('hLTRL8', models.CharField(default='', max_length=200)),
                ('hLTM60', models.CharField(default='', max_length=200)),
                ('v1000', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='codCaus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Componente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=128)),
                ('alias', models.CharField(default='', max_length=128)),
                ('shouldShow', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='ComponenteAPT5',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=128)),
                ('pieza', models.CharField(default='', max_length=128)),
                ('componente', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='f412.Componente')),
            ],
        ),
        migrations.CreateModel(
            name='costeHora',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(default=1)),
                ('precio', models.FloatField(default=1.0)),
            ],
        ),
        migrations.CreateModel(
            name='Defecto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=128)),
                ('alias', models.CharField(default='', max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Designacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=128)),
                ('alias', models.CharField(default='', max_length=128)),
                ('Componente', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='f412.Componente')),
            ],
        ),
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=128)),
                ('color', models.CharField(default=1, max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='F412',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Fecha', models.DateField(null=True)),
                ('Referencia', models.CharField(default='', max_length=128)),
                ('horas', models.CharField(default='', max_length=64)),
                ('horasAntiguas', models.CharField(default='', max_length=64, null=True)),
                ('nOp', models.CharField(default='', max_length=64, null=True)),
                ('horasRecurrentes', models.CharField(default='', max_length=64, null=True)),
                ('horasAntRec', models.CharField(default='', max_length=64, null=True)),
                ('Descripcion', models.CharField(default='', max_length=1024)),
                ('accion', models.CharField(default='', max_length=512, null=True)),
                ('nAV', models.IntegerField(default=1, null=True)),
                ('descripcionAcortada', models.CharField(default='', max_length=40, null=True)),
                ('rtMod', models.BooleanField(default=False)),
                ('operacion', models.CharField(default=1, max_length=40, null=True)),
                ('myID', models.IntegerField(default=1)),
                ('hnc', models.CharField(default='', max_length=40, null=True)),
                ('nDefecto', models.CharField(default='', max_length=40, null=True)),
                ('Area', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='f412.Area')),
                ('Componente', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='f412.Componente')),
                ('Defecto', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='f412.Defecto')),
                ('Designacion', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='f412.Designacion')),
                ('Estado', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='f412.Estado')),
            ],
        ),
        migrations.CreateModel(
            name='f412Ant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Fecha', models.DateField(null=True)),
                ('horas', models.CharField(default='', max_length=128)),
                ('myID', models.IntegerField(default=1)),
                ('Area', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='f412.Area')),
                ('Componente', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='f412.Componente')),
                ('Defecto', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='f412.Defecto')),
            ],
        ),
        migrations.CreateModel(
            name='modificaciones',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField(default=1)),
                ('fecha', models.DateField(null=True)),
                ('comentarios', models.CharField(default='', max_length=256)),
                ('estadoNuevo', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='estadoNuevo', to='f412.Estado')),
                ('estadoViejo', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='estadoViejo', to='f412.Estado')),
                ('f412', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='f412.F412')),
            ],
        ),
        migrations.CreateModel(
            name='myUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=256)),
                ('email', models.CharField(default='', max_length=256)),
                ('passwd', models.CharField(default='', max_length=128)),
                ('admin', models.BooleanField(default=False)),
                ('NA', models.CharField(default='', max_length=64)),
                ('nombreCompleto', models.CharField(default='', max_length=128)),
                ('quiereCorreo', models.BooleanField(default=False)),
                ('hasChosen', models.BooleanField(default=False)),
                ('isSuperUser', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='oldHour',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(default=1)),
                ('month', models.IntegerField(default=1)),
                ('hours', models.FloatField(default=0.0)),
                ('codCaus', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='f412.codCaus')),
                ('component', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='f412.Componente')),
            ],
        ),
        migrations.CreateModel(
            name='paretoDefecto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accion', models.CharField(default='', max_length=1024)),
                ('ppsCod', models.CharField(default='', max_length=256)),
                ('fechaApertura', models.DateField(null=True)),
                ('fechaCierre', models.DateField(null=True)),
                ('area', models.CharField(default='', max_length=256)),
                ('ahorro', models.CharField(default='', max_length=256)),
                ('isPPS', models.BooleanField(default=False)),
                ('modificadaFechaAp', models.BooleanField(default=False)),
                ('modificadaFechaCie', models.BooleanField(default=False)),
                ('number', models.IntegerField(default=1)),
                ('horas', models.FloatField(default=0.0)),
                ('defecto', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='f412.Defecto')),
            ],
        ),
        migrations.CreateModel(
            name='paretoTabla',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isLay', models.BooleanField(default=False)),
                ('year', models.IntegerField(default=2018)),
                ('mes', models.IntegerField(default=1)),
                ('pareto', models.CharField(default='', max_length=128)),
                ('topDefc', models.ManyToManyField(related_name='paretoTablaList', to='f412.paretoDefecto')),
            ],
        ),
        migrations.CreateModel(
            name='Pieza',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='planesCount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(default=1)),
                ('mes', models.IntegerField(default=1)),
                ('numPlanes', models.FloatField(default=0.0)),
                ('is380Tot', models.BooleanField(default=False)),
                ('component', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='f412.Componente')),
            ],
        ),
        migrations.CreateModel(
            name='PN',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=128)),
                ('Designacion', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='PN', to='f412.Designacion')),
            ],
        ),
        migrations.CreateModel(
            name='PNEvol',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=128)),
                ('shouldShow', models.BooleanField(default=True)),
                ('currentPN', models.BooleanField(default=True)),
                ('designation', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='f412.Designacion')),
                ('pn', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='f412.PN')),
            ],
        ),
        migrations.CreateModel(
            name='Programa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='reasonTree',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shortName', models.CharField(default='', max_length=13)),
                ('currentlyInUse', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='reasonTreeField',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nivel', models.IntegerField(default=1)),
                ('nombre', models.CharField(default='', max_length=100)),
                ('codigo', models.CharField(default='', max_length=3)),
                ('shortName', models.CharField(default='', max_length=7)),
                ('currentlyInUse', models.BooleanField(default=False)),
                ('superior', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='f412.reasonTreeField')),
            ],
        ),
        migrations.CreateModel(
            name='Reparacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Fecha', models.DateField(null=True)),
                ('Referencia', models.CharField(default='', max_length=128)),
                ('hnc', models.CharField(default='', max_length=128)),
                ('horas', models.CharField(default='', max_length=64)),
                ('nOp', models.CharField(default='', max_length=64)),
                ('horasLeadTime', models.CharField(default='', max_length=64)),
                ('Descripcion', models.CharField(default='', max_length=1024)),
                ('nAV', models.IntegerField(default=1)),
                ('myID', models.IntegerField(default=1)),
                ('rtMod', models.BooleanField(default=True)),
                ('Area', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='f412.Area')),
                ('Componente', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='f412.Componente')),
                ('Defecto', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='f412.Defecto')),
                ('Designacion', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='f412.Designacion')),
                ('LastChangeUser', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='reparacion_requests_created', to='f412.myUser')),
                ('PN', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='f412.PN')),
                ('Pieza', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='f412.Pieza')),
            ],
        ),
        migrations.CreateModel(
            name='Seccion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=128)),
                ('programa', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='f412.Programa')),
            ],
        ),
        migrations.CreateModel(
            name='sendMail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shouldSend', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='SGM',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(default='', max_length=128)),
                ('name', models.CharField(default='', max_length=128)),
                ('seccion', models.ManyToManyField(default=1, to='f412.Seccion')),
                ('user', models.ManyToManyField(default=1, to='f412.myUser')),
            ],
        ),
        migrations.CreateModel(
            name='tipoUsuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=128)),
            ],
        ),
        migrations.AddField(
            model_name='reparacion',
            name='SGM',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='f412.SGM'),
        ),
        migrations.AddField(
            model_name='reparacion',
            name='Usuario',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='f412.myUser'),
        ),
        migrations.AddField(
            model_name='reparacion',
            name='codigoCausa',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='f412.codCaus'),
        ),
        migrations.AddField(
            model_name='reparacion',
            name='pnEv',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='f412.PNEvol'),
        ),
        migrations.AddField(
            model_name='reparacion',
            name='programa',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='f412.Programa'),
        ),
        migrations.AddField(
            model_name='reparacion',
            name='reasonTree',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='f412.reasonTree'),
        ),
        migrations.AddField(
            model_name='reparacion',
            name='seccion',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='f412.Seccion'),
        ),
        migrations.AddField(
            model_name='reasontree',
            name='nivel1',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='lvl1', to='f412.reasonTreeField'),
        ),
        migrations.AddField(
            model_name='reasontree',
            name='nivel2',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='lvl2', to='f412.reasonTreeField'),
        ),
        migrations.AddField(
            model_name='reasontree',
            name='nivel3',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='lvl3', to='f412.reasonTreeField'),
        ),
        migrations.AddField(
            model_name='reasontree',
            name='program',
            field=models.ForeignKey(default=14, on_delete=django.db.models.deletion.PROTECT, to='f412.Programa'),
        ),
        migrations.AddField(
            model_name='pn',
            name='programa',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='f412.Programa'),
        ),
        migrations.AddField(
            model_name='planescount',
            name='program',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='f412.Programa'),
        ),
        migrations.AddField(
            model_name='oldhour',
            name='program',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='f412.Programa'),
        ),
        migrations.AddField(
            model_name='myuser',
            name='programa',
            field=models.ManyToManyField(to='f412.Programa'),
        ),
        migrations.AddField(
            model_name='myuser',
            name='seccion',
            field=models.ManyToManyField(default=1, to='f412.Seccion'),
        ),
        migrations.AddField(
            model_name='myuser',
            name='typeUser',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='f412.tipoUsuario'),
        ),
        migrations.AddField(
            model_name='myuser',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='modificaciones',
            name='usuario',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='f412.myUser'),
        ),
        migrations.AddField(
            model_name='f412',
            name='LastChangeUser',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='f412_requests_created', to='f412.myUser'),
        ),
        migrations.AddField(
            model_name='f412',
            name='PN',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='f412.PN'),
        ),
        migrations.AddField(
            model_name='f412',
            name='Pieza',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='f412.Pieza'),
        ),
        migrations.AddField(
            model_name='f412',
            name='SGM',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='f412.SGM'),
        ),
        migrations.AddField(
            model_name='f412',
            name='Usuario',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='f412.myUser'),
        ),
        migrations.AddField(
            model_name='f412',
            name='areaCaus',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='f412.areaCaus'),
        ),
        migrations.AddField(
            model_name='f412',
            name='codigoCausa',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.PROTECT, to='f412.codCaus'),
        ),
        migrations.AddField(
            model_name='f412',
            name='pnEv',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='f412.PNEvol'),
        ),
        migrations.AddField(
            model_name='f412',
            name='programa',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='f412.Programa'),
        ),
        migrations.AddField(
            model_name='f412',
            name='reasonTree',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.PROTECT, to='f412.reasonTree'),
        ),
        migrations.AddField(
            model_name='f412',
            name='seccion',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='f412.Seccion'),
        ),
        migrations.AddField(
            model_name='defecto',
            name='seccion',
            field=models.ManyToManyField(default=1, to='f412.Seccion'),
        ),
        migrations.AddField(
            model_name='componenteapt5',
            name='parNumber',
            field=models.ManyToManyField(default=1, to='f412.PN'),
        ),
        migrations.AddField(
            model_name='componente',
            name='programa',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='f412.Programa'),
        ),
        migrations.AddField(
            model_name='avion',
            name='f412List',
            field=models.ManyToManyField(default=1, to='f412.F412'),
        ),
        migrations.AddField(
            model_name='avion',
            name='repList',
            field=models.ManyToManyField(default=1, to='f412.Reparacion'),
        ),
        migrations.AddField(
            model_name='area',
            name='seccion',
            field=models.ManyToManyField(default=1, to='f412.Seccion'),
        ),
    ]
