# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-05-03 10:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('f412', '0011_f412_accion'),
    ]

    operations = [
        migrations.AddField(
            model_name='sgm',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='f412.myUser'),
        ),
    ]
