# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-05-04 07:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('f412', '0012_sgm_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sgm',
            name='user',
        ),
        migrations.AddField(
            model_name='sgm',
            name='user',
            field=models.ManyToManyField(default=1, to='f412.myUser'),
        ),
    ]
