# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-05-07 13:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('f412', '0013_auto_20180504_0944'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='name',
            field=models.CharField(default=1, max_length=256),
        ),
    ]
