# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-05-07 14:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('f412', '0014_myuser_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='tipoUsuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
            ],
        ),
        migrations.RemoveField(
            model_name='myuser',
            name='puedeCrear',
        ),
        migrations.AddField(
            model_name='myuser',
            name='typeUser',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='f412.tipoUsuario'),
        ),
    ]
