# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-05-09 06:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('f412', '0015_auto_20180507_1624'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='f412',
            name='pieza',
        ),
    ]
