# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-05-09 06:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('f412', '0016_remove_f412_pieza'),
    ]

    operations = [
        migrations.AddField(
            model_name='f412',
            name='pieza',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='f412.Pieza'),
        ),
    ]
