# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-05-09 06:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('f412', '0017_f412_pieza'),
    ]

    operations = [
        migrations.RenameField(
            model_name='f412',
            old_name='pieza',
            new_name='pepe',
        ),
    ]
