# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-05-09 06:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('f412', '0018_auto_20180509_0802'),
    ]

    operations = [
        migrations.RenameField(
            model_name='f412',
            old_name='pepe',
            new_name='pieza',
        ),
    ]
