# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-05-09 06:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('f412', '0020_auto_20180509_0803'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='f412',
            name='Pieza',
        ),
        migrations.DeleteModel(
            name='Pieza',
        ),
    ]
