# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-05-11 07:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('f412', '0023_estado_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='f412',
            name='comentarioAcortado',
            field=models.CharField(default='', max_length=40),
        ),
    ]
