# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-05-11 07:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('f412', '0024_f412_comentarioacortado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='f412',
            name='Descripcion',
            field=models.CharField(default='', max_length=1024),
        ),
    ]
