# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-05-11 08:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('f412', '0025_auto_20180511_0910'),
    ]

    operations = [
        migrations.RenameField(
            model_name='f412',
            old_name='comentarioAcortado',
            new_name='descripcionAcortada',
        ),
    ]
