# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-05-14 06:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('f412', '0026_auto_20180511_1042'),
    ]

    operations = [
        migrations.CreateModel(
            name='reasonTree',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='reasonTreeField',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nivel', models.IntegerField(default=1)),
                ('nombre', models.CharField(default='', max_length=100)),
                ('codigo', models.CharField(default='', max_length=3)),
            ],
        ),
        migrations.AddField(
            model_name='reasontree',
            name='nivel1',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='lvl1', to='f412.reasonTreeField'),
        ),
        migrations.AddField(
            model_name='reasontree',
            name='nivel2',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='lvl2', to='f412.reasonTreeField'),
        ),
        migrations.AddField(
            model_name='reasontree',
            name='nivel3',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='lvl3', to='f412.reasonTreeField'),
        ),
        migrations.AddField(
            model_name='f412',
            name='reasonTree',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='f412.reasonTree'),
        ),
    ]
