# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-05-14 07:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('f412', '0027_auto_20180514_0852'),
    ]

    operations = [
        migrations.AddField(
            model_name='reasontreefield',
            name='superior',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='f412.reasonTreeField'),
        ),
    ]
