# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-05-14 08:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('f412', '0028_reasontreefield_superior'),
    ]

    operations = [
        migrations.AddField(
            model_name='reasontreefield',
            name='shortName',
            field=models.CharField(default='', max_length=7),
        ),
    ]
