# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-05-15 06:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('f412', '0030_myuser_ng'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myuser',
            name='seccion',
        ),
        migrations.AddField(
            model_name='myuser',
            name='seccion',
            field=models.ManyToManyField(default=1, to='f412.Seccion'),
        ),
    ]
