# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-05-16 08:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('f412', '0031_auto_20180515_0822'),
    ]

    operations = [
        migrations.AddField(
            model_name='reasontree',
            name='shortName',
            field=models.CharField(default='', max_length=13),
        ),
    ]
