# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-05-17 08:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('f412', '0038_auto_20180516_1230'),
    ]

    operations = [
        migrations.RenameField(
            model_name='myuser',
            old_name='NG',
            new_name='NA',
        ),
    ]
