# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-05-17 09:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('f412', '0039_auto_20180517_1056'),
    ]

    operations = [
        migrations.AddField(
            model_name='f412',
            name='horasAntiguas',
            field=models.CharField(default='', max_length=64),
        ),
    ]
