# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-05-24 06:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('f412', '0040_f412_horasantiguas'),
    ]

    operations = [
        migrations.AddField(
            model_name='f412',
            name='nOp',
            field=models.CharField(default='', max_length=64),
        ),
    ]
