# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-05-24 06:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('f412', '0041_f412_nop'),
    ]

    operations = [
        migrations.AddField(
            model_name='f412',
            name='horasAntRec',
            field=models.CharField(default='', max_length=64),
        ),
        migrations.AddField(
            model_name='f412',
            name='horasRecurrentes',
            field=models.CharField(default='', max_length=64),
        ),
    ]
