# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-05-24 08:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('f412', '0042_auto_20180524_0856'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='nombreCompleto',
            field=models.CharField(default='', max_length=128),
        ),
    ]
