# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-05-30 13:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('f412', '0043_myuser_nombrecompleto'),
    ]

    operations = [
        migrations.CreateModel(
            name='modificaciones',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField(default=1)),
                ('fecha', models.DateField()),
                ('comentarios', models.CharField(default='', max_length=256)),
                ('estadoNuevo', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='estadoNuevo', to='f412.Estado')),
                ('estadoViejo', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='estadoViejo', to='f412.Estado')),
            ],
        ),
        migrations.AddField(
            model_name='f412',
            name='operacion',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='modificaciones',
            name='f412',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='f412.F412'),
        ),
        migrations.AddField(
            model_name='modificaciones',
            name='usuario',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='f412.myUser'),
        ),
    ]
