# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-05-30 10:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('f412', '0043_myuser_nombrecompleto'),
    ]

    operations = [
        migrations.CreateModel(
            name='modificacioens',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField(default=1)),
                ('fecha', models.DateField()),
                ('f412', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='f412.F412')),
                ('usuario', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='f412.myUser')),
            ],
        ),
    ]
