# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-06-04 14:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('f412', '0044_auto_20180530_1559'),
    ]

    operations = [
        migrations.CreateModel(
            name='codCaus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
            ],
        ),
        migrations.AddField(
            model_name='f412',
            name='codigoCausa',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='f412.codCaus'),
        ),
    ]
