# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-05-30 10:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('f412', '0044_modificacioens'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='modificacioens',
            new_name='modificaciones',
        ),
    ]
