# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-05-30 10:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('f412', '0045_auto_20180530_1249'),
    ]

    operations = [
        migrations.AddField(
            model_name='modificaciones',
            name='comentarios',
            field=models.CharField(default='', max_length=256),
        ),
    ]
