# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-05-30 10:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('f412', '0046_modificaciones_comentarios'),
    ]

    operations = [
        migrations.AddField(
            model_name='modificaciones',
            name='estadoNuevo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='f412.Estado'),
        ),
        migrations.AddField(
            model_name='modificaciones',
            name='estadoViejo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='f412.Estado'),
        ),
    ]
