# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-05-30 10:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('f412', '0047_auto_20180530_1253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modificaciones',
            name='estadoNuevo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='estadoViejo', to='f412.Estado'),
        ),
        migrations.AlterField(
            model_name='modificaciones',
            name='estadoViejo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='estadoViejo', to='f412.Estado'),
        ),
    ]
