# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-06-04 14:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('f412', '0047_auto_20180604_1618'),
    ]

    operations = [
        migrations.AlterField(
            model_name='f412',
            name='operacion',
            field=models.CharField(default=1, max_length=100),
        ),
    ]
