# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-05-30 13:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('f412', '0049_auto_20180530_1254'),
    ]

    operations = [
        migrations.AddField(
            model_name='f412',
            name='operacion',
            field=models.IntegerField(default=1),
        ),
    ]
