# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-06-04 09:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('f412', '0052_auto_20180604_1032'),
    ]

    operations = [
        migrations.CreateModel(
            name='codCaus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
            ],
        ),
    ]
