# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-06-04 14:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('f412', '0054_f412_codigocausa'),
        ('f412', '0050_auto_20180604_1621'),
    ]

    operations = [
    ]
