# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-06-04 14:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('f412', '0054_f412_codigocausa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='f412',
            name='operacion',
            field=models.CharField(default=1),
        ),
    ]
