# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-06-04 14:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('f412', '0056_auto_20180604_1626'),
    ]

    operations = [
        migrations.AddField(
            model_name='f412',
            name='operacionChar',
            field=models.CharField(default='', max_length=100),
        ),
    ]
