# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-06-04 14:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('f412', '0056_auto_20180604_1640'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='f412',
            name='operacion',
        ),
    ]
