# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-06-04 14:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('f412', '0057_remove_f412_operacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='f412',
            name='operacion',
            field=models.IntegerField(default=1),
        ),
    ]
