# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-06-05 06:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('f412', '0059_auto_20180604_1653'),
        ('f412', '0060_auto_20180604_1651'),
    ]

    operations = [
    ]
