# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-06-05 07:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('f412', '0062_auto_20180605_0807'),
    ]

    operations = [
        migrations.AddField(
            model_name='f412',
            name='operacionChar',
            field=models.CharField(default=1, max_length=40),
        ),
    ]
