# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-06-05 07:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('f412', '0063_f412_operacionchar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='f412',
            name='operacion',
        ),
    ]
