# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-06-06 09:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('f412', '0068_f412_rtmod'),
    ]

    operations = [
        migrations.AddField(
            model_name='componente',
            name='alias',
            field=models.CharField(default='', max_length=128),
        ),
        migrations.AddField(
            model_name='defecto',
            name='alias',
            field=models.CharField(default='', max_length=128),
        ),
        migrations.AddField(
            model_name='designacion',
            name='alias',
            field=models.CharField(default='', max_length=128),
        ),
    ]
