# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-06-11 09:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('f412', '0069_auto_20180606_1146'),
    ]

    operations = [
        migrations.CreateModel(
            name='avion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField(default=1)),
                ('hRecALB', models.CharField(default='', max_length=200)),
                ('hRecV10', models.CharField(default='', max_length=200)),
                ('hRecRL8', models.CharField(default='', max_length=200)),
                ('hRecM60', models.CharField(default='', max_length=200)),
                ('hLTALB', models.CharField(default='', max_length=200)),
                ('hLTV10', models.CharField(default='', max_length=200)),
                ('hLTRL8', models.CharField(default='', max_length=200)),
                ('hLTM60', models.CharField(default='', max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='f412',
            name='añadidoAv',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='f412',
            name='avion',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='f412.avion'),
        ),
    ]
