# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-06-14 13:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('f412', '0071_avion_v1000'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComponenteAPT5',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=128)),
                ('pieza', models.CharField(default='', max_length=128)),
                ('componente', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='f412.Componente')),
                ('parNumber', models.ManyToManyField(default=1, to='f412.PN')),
            ],
        ),
    ]
