# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-06-19 10:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('f412', '0072_componenteapt5'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reparacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Fecha', models.DateField()),
                ('Referencia', models.CharField(default='', max_length=128)),
                ('hnc', models.CharField(default='', max_length=128)),
                ('horas', models.CharField(default='', max_length=64)),
                ('nOp', models.CharField(default='', max_length=64)),
                ('horasLeadTime', models.CharField(default='', max_length=64)),
                ('Descripcion', models.CharField(default='', max_length=1024)),
                ('nAV', models.IntegerField(default=1)),
                ('añadidoAv', models.BooleanField(default=False)),
                ('myID', models.IntegerField(default=1)),
                ('Area', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='f412.Area')),
                ('Componente', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='f412.Componente')),
                ('Defecto', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='f412.Defecto')),
                ('Designacion', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='f412.Designacion')),
                ('LastChangeUser', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='reparacion_requests_created', to='f412.myUser')),
                ('PN', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='f412.PN')),
                ('Pieza', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='f412.Pieza')),
                ('SGM', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='f412.SGM')),
                ('Usuario', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='f412.myUser')),
                ('avion', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='f412.avion')),
                ('codigoCausa', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='f412.codCaus')),
                ('programa', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='f412.Programa')),
            ],
        ),
        migrations.AddField(
            model_name='reasontree',
            name='program',
            field=models.ForeignKey(default=14, on_delete=django.db.models.deletion.CASCADE, to='f412.Programa'),
        ),
        migrations.AddField(
            model_name='reparacion',
            name='reasonTree',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='f412.reasonTree'),
        ),
        migrations.AddField(
            model_name='reparacion',
            name='seccion',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='f412.Seccion'),
        ),
    ]
