# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-07-12 11:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('f412', '0073_auto_20180619_1240'),
    ]

    operations = [
        migrations.CreateModel(
            name='costeHora',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(default=1)),
                ('precio', models.FloatField(default=1.0)),
            ],
        ),
        migrations.CreateModel(
            name='f412Ant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Fecha', models.DateField()),
                ('horas', models.CharField(default='', max_length=128)),
                ('myID', models.IntegerField(default=1)),
                ('Area', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='f412.Area')),
                ('Componente', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='f412.Componente')),
                ('Defecto', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='f412.Defecto')),
            ],
        ),
        migrations.CreateModel(
            name='paretoDefecto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accion', models.CharField(default='', max_length=1024)),
                ('ppsCod', models.CharField(default='', max_length=256)),
                ('fechaApertura', models.DateField(null=True)),
                ('fechaCierre', models.DateField(null=True)),
                ('area', models.CharField(default='', max_length=256)),
                ('ahorro', models.CharField(default='', max_length=256)),
                ('isPPS', models.BooleanField(default=False)),
                ('modificadaFechaAp', models.BooleanField(default=False)),
                ('modificadaFechaCie', models.BooleanField(default=False)),
                ('number', models.IntegerField(default=1)),
                ('defecto', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='f412.Defecto')),
            ],
        ),
        migrations.CreateModel(
            name='paretoTabla',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isLay', models.BooleanField(default=False)),
                ('year', models.IntegerField(default=2018)),
                ('mes', models.IntegerField(default=1)),
                ('pareto', models.CharField(default='', max_length=128)),
                ('topDefc', models.ManyToManyField(to='f412.paretoDefecto')),
            ],
        ),
        migrations.RemoveField(
            model_name='f412',
            name='avion',
        ),
        migrations.RemoveField(
            model_name='f412',
            name='añadidoAv',
        ),
        migrations.RemoveField(
            model_name='reparacion',
            name='avion',
        ),
        migrations.RemoveField(
            model_name='reparacion',
            name='añadidoAv',
        ),
        migrations.AddField(
            model_name='avion',
            name='f412List',
            field=models.ManyToManyField(default=1, to='f412.F412'),
        ),
        migrations.AddField(
            model_name='avion',
            name='repList',
            field=models.ManyToManyField(default=1, to='f412.Reparacion'),
        ),
        migrations.AlterField(
            model_name='f412',
            name='accion',
            field=models.CharField(default='', max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='f412',
            name='codigoCausa',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='f412.codCaus'),
        ),
        migrations.AlterField(
            model_name='f412',
            name='descripcionAcortada',
            field=models.CharField(default='', max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='f412',
            name='horasAntRec',
            field=models.CharField(default='', max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='f412',
            name='horasAntiguas',
            field=models.CharField(default='', max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='f412',
            name='horasRecurrentes',
            field=models.CharField(default='', max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='f412',
            name='nAV',
            field=models.IntegerField(default=1, null=True),
        ),
        migrations.AlterField(
            model_name='f412',
            name='nOp',
            field=models.CharField(default='', max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='f412',
            name='operacion',
            field=models.CharField(default=1, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='f412',
            name='reasonTree',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='f412.reasonTree'),
        ),
    ]
