# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-10-05 07:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('f412', '0074_auto_20180712_1310'),
    ]

    operations = [
        migrations.CreateModel(
            name='areaCaus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('code', models.CharField(max_length=3)),
            ],
        ),
    ]
