# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-10-05 07:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('f412', '0075_areacaus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='areacaus',
            name='code',
            field=models.CharField(max_length=10),
        ),
    ]
