# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-10-05 07:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('f412', '0076_auto_20181005_0908'),
    ]

    operations = [
        migrations.AddField(
            model_name='f412',
            name='areaCaus',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='f412.areaCaus'),
        ),
    ]
