# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-10-15 14:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('f412', '0082_auto_20181015_0843'),
    ]

    operations = [
        migrations.AddField(
            model_name='f412',
            name='nDefecto',
            field=models.CharField(default='', max_length=40, null=True),
        ),
    ]
