# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-10-23 09:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('f412', '0083_f412_ndefecto'),
    ]

    operations = [
        migrations.CreateModel(
            name='quiereCorreo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quiere', models.BooleanField(default=False)),
                ('hasChoosen', models.BooleanField(default=False)),
            ],
        ),
    ]
