# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-10-23 09:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('f412', '0084_quierecorreo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='quiereCorreo',
        ),
        migrations.AddField(
            model_name='myuser',
            name='hasChoosen',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='myuser',
            name='quiere',
            field=models.BooleanField(default=False),
        ),
    ]
