# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-10-23 09:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('f412', '0085_auto_20181023_1128'),
    ]

    operations = [
        migrations.RenameField(
            model_name='myuser',
            old_name='quiere',
            new_name='quiereCorreo',
        ),
    ]
