# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-10-24 06:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('f412', '0086_auto_20181023_1129'),
    ]

    operations = [
        migrations.RenameField(
            model_name='myuser',
            old_name='hasChoosen',
            new_name='hasChosen',
        ),
    ]
