# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-11-14 10:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('f412', '0087_auto_20181024_0855'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='isSuperUser',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='paretotabla',
            name='topDefc',
            field=models.ManyToManyField(related_name='paretoTablaList', to='f412.paretoDefecto'),
        ),
        migrations.AlterField(
            model_name='pn',
            name='Designacion',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='PN', to='f412.Designacion'),
        ),
    ]
