# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-11-23 10:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('f412', '0088_auto_20181114_1146'),
    ]

    operations = [
        migrations.AddField(
            model_name='reasontree',
            name='currentlyInUse',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='reasontreefield',
            name='currentlyInUse',
            field=models.BooleanField(default=False),
        ),
    ]
