# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-11-27 09:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('f412', '0091_auto_20181123_1230'),
    ]

    operations = [
        migrations.CreateModel(
            name='sendMail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shouldSend', models.BooleanField(default=True)),
            ],
        ),
    ]
