# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-11-28 07:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('f412', '0092_sendmail'),
    ]

    operations = [
        migrations.AddField(
            model_name='paretodefecto',
            name='horas',
            field=models.FloatField(default=0.0),
        ),
    ]
