# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-12-05 15:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('f412', '0093_paretodefecto_horas'),
    ]

    operations = [
        migrations.CreateModel(
            name='planesCount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(default=1)),
                ('mes', models.IntegerField(default=1)),
                ('numPlanes', models.FloatField(default=0.0)),
                ('component', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='f412.Componente')),
                ('program', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='f412.Programa')),
            ],
        ),
    ]
