# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-12-13 10:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('f412', '0095_appyears_oldhour'),
    ]

    operations = [
        migrations.AddField(
            model_name='componente',
            name='shouldShow',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='reparacion',
            name='rtMod',
            field=models.BooleanField(default=True),
        ),
    ]
